package skyline.tw.simple.date.model;

import org.joda.time.DateTime;

import java.util.Date;

// domain model
public class User {

    public Date birthday;
    private String firstName;
    private String lastName;
    private String nickName;

    public User(){
    }

    public User(Date birthday, String firstName, String lastName, String nickName){
        this.birthday = birthday;
        this.firstName = firstName;
        this.lastName = lastName;
        this.nickName = nickName;
    }

    @Override
    public String toString() {
        return "\nHi Im " + firstName + " " + lastName + ".\n"
                + "Im " + getAge() + " years old and my birthday is " + birthday + ".\n"
                + "You can call me '" + nickName + "'\n";
    }

    /**
     * Automatically generated by intelliJ
     */
    public int getAge() {
        int currentYear = DateTime.now().getYear();
        int birthYear = new DateTime(birthday).getYear();
        return currentYear - birthYear;
    }

    public Date getBirthday() {
        return birthday;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getNickName() {
        return nickName;
    }
    
    public String getName(){
        return firstName + " " + lastName;
    }
}
